// All code in this file is generated by generate_mapping_c.py.  Do not edit it, use the code-generation folder instead
#include <pebble.h>
#define NUM_CONDITION_CODES %NUM_CONDITION_CODES%
#define ERROR_ICON 24;

uint8_t condition_code_to_icon(uint8_t condition_code) {
	static const uint8_t lookup[NUM_CONDITION_CODES] = %CONDITION_CODE_TO_ICON_TABLE%;

	if(condition_code < NUM_CONDITION_CODES) {
		return lookup[condition_code];
	}

	return ERROR_ICON;
}

/*
uint8_t condition_code_to_string(uint8_t condition_code) {
	// Not needed yet but likely
}
*/